core/urls.py
from django.urls import path
from core import views, transfer, transaction, payment_request, credit_card


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),

    #personal
    path('payments-01.html', views.payments, name='payments'),
    path('subscriptions.html', views.subscriptions, name='subscriptions'),
    path('security.html', views.security, name='security'),
    path('fees.html', views.fees, name='fees'),

    #business
    path('business-account.html', views.business_account, name='business-account'),
    path('corporate-card.html', views.corporate_card, name='corporate-card'),
    path('expense-management.html', views.expense_management, name='expense-management'),
    path('budgeting-and-analytics.html', views.budgeting_and_analytics, name='budgeting-and-analytics'),
    path('integrations.html', views.integrations, name='integrations'),
    path('invoice-management.html', views.invoice_management, name='invoice-management'),
    path('rewards.html', views.rewards, name='rewards'),

    #company
    path('about.html', views.about, name='about'),
    path('career.html', views.career, name='career'),
    path('career-details.html', views.career_details, name='career-details'),
    path('blog-details.html', views.blog_details, name='blog-details'),
    path('blog.html', views.blog, name='blog'),
    path('error.html', views.error, name='error'),

    #help
    path('help-center.html', views.help_center, name='help-center'),
    path('help-center-category.html', views.help_center_category, name='help-center-category'),
    
    #dashboard
    path('crypto.html', views.crypto, name='crypto'),
    path('deposit-money.html', views.deposit_money, name='deposit-money'),
    path('money-exchange.html', views.money_exchange, name='money-exchange'),
    path('recipients.html', views.recipients, name='recipients'),
    path('withdraw-money-step-1.html', views.withdraw_money, name='withdraw-money'),

    # Transfers
    path("search-account/", transfer.search_users_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.AmountTransfer, name="amount-transfer"),
    path("amount-transfer-process/<account_number>/", transfer.AmountTransferProcess, name="amount-transfer-process"),
    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.TransferConfirmation, name="transfer-confirmation"),
    path("transfer-process/<account_number>/<transaction_id>/", transfer.TransferProcess, name="transfer-process"),
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.TransferCompleted, name="transfer-completed"),


    # transactions
    path("transactions/", transaction.transaction_lists, name="transactions"),
    path("transaction-detail/<transaction_id>/", transaction.transaction_detail, name="transaction-detail"),

    # Payment Request
    path("request-search-account/", payment_request.SearchUsersRequest, name="request-search-account"),
    path("amount-request/<account_number>/", payment_request.AmountRequest, name="amount-request"),
    path("amount-request-process/<account_number>/", payment_request.AmountRequestProcess, name="amount-request-process"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.AmountRequestConfirmation, name="amount-request-confirmation"),
    path("amount-request-final-process/<account_number>/<transaction_id>/", payment_request.AmountRequestFinalProcess, name="amount-request-final-process"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.RequestCompleted, name="amount-request-completed"),


    # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settlement_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.SettlementCompleted, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.deletepaymentrequest, name="delete-request"),



    # Credit Card URLS
    path("card/<card_id>/", credit_card.card_detail, name="card-detail"),
    path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
    path("withdraw_fund/<card_id>/", credit_card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>/", credit_card.delete_card, name="delete_card"),
]

paylio/urls.py
 

from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static
from django.conf import settings
import os
from core.views import AdminLogoutView  # Adjust if placed elsewhere
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/logout/', AdminLogoutView.as_view(), name='admin-logout'),   
    path("admin/", admin.site.urls),
    path("", include("core.urls")),  
    path("", views.index, name="index"), 
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("user/", include("userauths.urls")),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    path('google3797164cdd298408.html', TemplateView.as_view(template_name='google3797164cdd298408.html', content_type='text/html')),

]
 

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'paylio', 'static'))

# Serve media files in both DEBUG and production
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path, include
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.LoginView, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Roanokeheritage - Online Banking</title>

  <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image/x-icon" />
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
    integrity="sha512-M...==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/banking-enhancements.css' %}" />
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>

<body>
  <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

  <header class="header-section">
    <div class="overlay">
      <div class="container">
        <div class="row d-flex header-area">
          <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{% url 'core:index' %}">
              <img src="{% static 'assets/images/logo.png' %}" class="logo" alt="logo" />
            </a>
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbar-content">
              <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
              <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown main-navbar">
                  <a class="nav-link " href="javascript:void(0)" data-bs-toggle="dropdown"
                    data-bs-auto-close="outside">Personal</a>
                  <ul class="dropdown-menu main-menu shadow">
                    <li><a class="nav-link" href="{% url 'core:payments' %}">Checking Accounts</a></li>
                    <li><a class="nav-link" href="{% url 'core:subscriptions' %}">Savings Accounts</a></li>
                    <li><a class="nav-link" href="{% url 'core:security' %}">Personal Loans</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown main-navbar">
                  <a class="nav-link " href="javascript:void(0)" data-bs-toggle="dropdown"
                    data-bs-auto-close="outside">Business</a>
                  <ul class="dropdown-menu main-menu shadow">
                    <li><a class="nav-link" href="{% url 'core:business-account' %}">Business Checking</a></li>
                    <li><a class="nav-link" href="{% url 'core:corporate-card' %}">Business Credit Cards</a></li>
                    <li><a class="nav-link" href="{% url 'core:expense-management' %}">Merchant Services</a></li>
                    <li><a class="nav-link" href="{% url 'core:budgeting-and-analytics' %}">Business Loans</a>
                    </li>
                    <li><a class="nav-link" href="{% url 'core:integrations' %}">Cash Management</a></li>
                    <li><a class="nav-link" href="{% url 'core:invoice-management' %}">Payroll Services</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:about' %}">About Us</a>
                </li>
              </ul>
              <div class="right-area header-action d-flex align-items-center max-un">
                {% if request.user.is_authenticated %}
                <a href="/admin" class="login cmdn-btn">Admin</a>
                <a href="{% url 'userauths:sign-out' %}" class="login cmn-btn">Sign Out</a>
                {% else %}
                <a href="{% url 'userauths:sign-in' %}" class="login">Login</a>
                <a href="{% url 'userauths:sign-up' %}" class="cmn-btn">Sign Up
                  <i class="fas fa-caret-right"></i>
                </a>
                {% endif %}
              </div>
            </div>
          </nav>
        </div>
        <!-- alert start -->
        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
          <strong>{{ message }}</strong>
        </div>
        {% endfor %} {% endif %}
        <script>
          setTimeout(() => {
            $(".alert").alert("close");
          }, 4000);
        </script>
        <!-- alert end -->
      </div>
    </div>
  </header>
  <!-- header-section end -->

  {% block content %} {% endblock content %}

  <!--==================================================================-->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/fontawesome.js' %}"></script>
  <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
  <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
  <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
  <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
  <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/banking-animations.js' %}"></script>
</body>

</html>